In [1]:
print("Hello World")

Hello World


In [2]:
#create numpy/ n-d arrays
import numpy as np

In [3]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [4]:
type(arr1)

numpy.ndarray

In [5]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
type(arr2)

numpy.ndarray

In [7]:
arr3 = np.zeroes((2.3))
arr3

AttributeError: module 'numpy' has no attribute 'zeroes'

In [8]:
arr3 = np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
arr4 = np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
arr5 = np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
arr6 = np.arrange(10)
arr6

AttributeError: module 'numpy' has no attribute 'arrange'

In [12]:
arr6 = np.arange(10)
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr7 = np.arange(5,16)
arr7

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [14]:
arr8 = np.arange(5,16,2)
arr8

array([ 5,  7,  9, 11, 13, 15])

In [15]:
arr9 = np.linspace(10,20,10)
arr9

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [16]:
arr10 = np.linspace(3,9,3)
arr10

array([3., 6., 9.])

In [17]:
arr11= arr10.copy()
arr11

array([3., 6., 9.])

In [18]:
#Numpy Array Properties and attributes
arr1

array([1, 2, 3, 4, 5])

In [19]:
arr1.shape

(5,)

In [20]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
arr2.shape

(2, 3)

In [23]:
arr12= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr12

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [26]:
arr12.shape

(2, 2, 2)

In [27]:
arr12.ndim

3

In [28]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
arr2.ndim

2

In [30]:
arr1

array([1, 2, 3, 4, 5])

In [31]:
arr1.ndim

1

In [35]:
arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr.shape

(2, 2, 2)

In [36]:
arr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [37]:
arr.size

8

In [38]:
arr.itemsize

4

In [39]:
item = np.array([11.11111111, 12.22222222, 13.33333333 ])
item.itemsize

8

In [40]:
item.dtype

dtype('float64')

In [41]:
arr.dtype

dtype('int32')

In [42]:
arr1

array([1, 2, 3, 4, 5])

In [43]:
arr1.astype('float')

array([1., 2., 3., 4., 5.])

In [3]:
lista = range(100)
import numpy as np
arr15 = np.arange(100)

In [1]:
print("Hello")

Hello


In [4]:
import numpy as np

In [5]:
list = range(100)
arr = np.arange(100)
import sys
print(sys.getsizeof(87)*len(list))
print(arr.itemsize*arr.size)

2800
400


In [8]:
import time
x = range(10000000)
y = range(10000000,20000000)

start_time = time.time()

c = [x+y for x,y in zip(x,y)]

print(time.time()-start_time)

1.7177860736846924


In [9]:
a = np.arange(10000000)
b = np.arange(10000000,20000000)
start_time = time.time()
c = a+b
print(time.time()-start_time)

0.18616867065429688


In [10]:
arr1 = np.arange(24).reshape(6,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [12]:
arr2 = np.array([1,2,3,4,5])
arr2[3]

4

In [14]:
arr2[2:4]

array([3, 4])

In [15]:
arr2[-1]

5

In [16]:
arr1[2]

array([ 8,  9, 10, 11])

In [17]:
arr1[:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [24]:
arr1[:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [25]:
arr1[:,2]

array([ 2,  6, 10, 14, 18, 22])

In [26]:
arr1[:,2:4]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])

In [27]:
arr1[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [29]:
arr1[4:,2:]

array([[18, 19],
       [22, 23]])

In [30]:
#Iteration
for i in arr1:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [31]:
for i in np.nditer(arr1):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
